[package]
name = "imgrab"
version = "0.4.0"
authors = ["Keep Calm <keepcalmandbyo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
directories = "3.0.1"
fmtsize = "0.1.1"
regex = "1.4.5"
reqwest = { version = "0.11.2", features = ["blocking", "cookies", "json"] }
scraper = "0.12.0"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
structopt = "0.3.21"
url = "2.2.1"
urlencoding = "1.1.1"
