[package]
name = "imgrab"
version = "0.7.0"
authors = ["Keep Calm <keepcalmandbyo@gmail.com>"]
edition = "2018"
include = ["src/**/*", "README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
directories = "4.0.1"
fmtsize = "0.1.1"
nipper = "0.1.9"
pathdiff = "0.2.0"
regex = "1.5.4"
reqwest = { version = "0.11.4", features = ["blocking", "cookies", "json"] }
scraper = "0.12.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
structopt = "0.3.23"
url = "2.2.2"
urlencoding = "2.1.0"
